# Generated by Django 4.0 on 2021-12-29 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('city', models.CharField(max_length=200)),
                ('sunrise', models.TimeField()),
                ('sunset', models.TimeField()),
                ('tempC', models.FloatField()),
                ('tempF', models.FloatField()),
                ('feels_like', models.FloatField()),
                ('pressure', models.FloatField()),
                ('humidity', models.FloatField()),
                ('dew_point', models.FloatField()),
                ('clouds', models.FloatField()),
                ('wind_speed', models.FloatField()),
                ('wind_gust', models.FloatField()),
                ('wind_deg', models.FloatField()),
                ('weather_description', models.CharField(max_length=200)),
                ('rain', models.FloatField()),
                ('snow', models.FloatField()),
                ('uvi', models.FloatField()),
                ('visibility', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Temperature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('tempC', models.FloatField()),
                ('tempF', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('sensor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensor_web_api.sensor')),
            ],
        ),
        migrations.CreateModel(
            name='Sound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('noise', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('sensor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensor_web_api.sensor')),
            ],
        ),
        migrations.CreateModel(
            name='Humidity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('humidity', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('sensor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensor_web_api.sensor')),
            ],
        ),
    ]
