# Generated by Django 4.0 on 2021-12-30 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensor_web_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='humidity',
            old_name='sensor_id',
            new_name='sensor',
        ),
        migrations.RenameField(
            model_name='sound',
            old_name='sensor_id',
            new_name='sensor',
        ),
        migrations.RenameField(
            model_name='temperature',
            old_name='sensor_id',
            new_name='sensor',
        ),
    ]
