# Generated by Django 4.0 on 2021-12-30 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensor_web_api', '0002_rename_sensor_id_humidity_sensor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='temperature',
            old_name='tempC',
            new_name='temp_c',
        ),
        migrations.RenameField(
            model_name='temperature',
            old_name='tempF',
            new_name='temp_f',
        ),
        migrations.RenameField(
            model_name='weather',
            old_name='tempC',
            new_name='temp_c',
        ),
        migrations.RenameField(
            model_name='weather',
            old_name='tempF',
            new_name='temp_f',
        ),
    ]
